// constants.js
export const Colors = {
    blue: '#2852BC',
    black: '#000',
    background: '#F5F5F5',
    red: '#FF0000',
    sky: '#91c8f2',
    placeColor: '#a5a8a5',
not_availe: '#0F2167',
booking_slelect: 'rgba(99,141,239,1)',
};

export const Strings = {
    Iagreewith: 'I agree with all term & conditions and privacy polices',
    loginButtonText: 'Login',
    signUpButtonText: 'Sign Up',

    ReEmailKey: 'ReEmailKey',
    ReNameKey: 'ReNameKey',
    RephoneKey: 'RephoneKey',
    RepasswordKey: 'RepasswordKey',
    ReCopasswordKey: 'ReCopasswordKey',
    ReAddressKey: 'ReAddressKey',
    ReUpiKey: 'ReUpiKey',
    ReCompanyKey: 'ReCompanyKey',

    BoxNameKey: 'BoxNameKey',
    BoxAddKey: 'BoxAddKey',
    BoxLenthKey: 'BoxLenthKey',
    BoxWidthKey: 'BoxWidthKey',
    BoxheightKey: 'BoxheightKey',
    BoxOpenKey: 'BoxOpenKey',
    BoxCloseKey: 'BoxCloseKey',
    BoxImageKey: 'BoxImageKey',


    MOpenKey: 'MOpenKey',
    MCloseKey: 'MCloseKey',
    MPriceKey: 'MPriceKey',
    AOpenKey: 'AOpenKey',
    ACloseKey: 'ACloseKey',
    APriceKey: 'APriceKey',
    EOpenKey: 'EOpenKey',
    ECloseKey: 'ECloseKey',
    EPriceKey: 'EPriceKey',

    SMPriceKey: 'SMPriceKey',
    SAPriceKey: 'SAPriceKey',
    SEPriceKey: 'SEPriceKey',

    TournamentPriceKey: 'TournamentPriceKey',
    STournamentPriceKey: 'STournamentPriceKey',

    SportKey: 'SportKey',
    FacilityKey: 'FacilityKey',
    TermKey: 'TermKey',
    AmountKey: 'AmountKey',

    BoxItemKey: 'BoxItemKey',


    AdminRegisterType: 'AdminRegisterType',
    PassChangeType: 'PassChangeType',
};

export const Routs = {
    BottomTabScreen: 'BottomTabScreen',
    CancelReqScreen: 'CancelReqScreen',
    InboxScreen: 'InboxScreen',
    EditBoxDScreen: 'EditBoxDScreen',
    LoginScreen: 'LoginScreen',
    Registerscreen: 'Registerscreen',
    OtpScreen: 'OtpScreen',
    AdminRegister: 'AdminRegister',
    SportScreen: 'SportScreen',
    TimeScreen: 'TimeScreen',
    RulesScreen: 'RulesScreen',
    HomeScreen: 'HomeScreen',
    DrawerScreen: 'DrawerScreen',
    BoxDetailsScreen: 'BoxDetailsScreen',
    DateTimeScreen: 'DateTimeScreen',
    ChangePassword: 'ChangePassword'
}
export const ImagePath = {

    bgmain: require('../../assets/Image/bgmain.png'),
    // bgmain: require('../../assets/Image/Frame.jpg'),
    boll: require('../../assets/Image/boll.png'),
    mail: require('../../assets/Image/mail.png'),
    user: require('../../assets/Image/user.png'),
    password: require('../../assets/Image/password.png'),
    hide: require('../../assets/Image/hide.png'),
    view: require('../../assets/Image/view.png'),
    emailsent: require('../../assets/Image/emailsent.png'),
    telephone: require('../../assets/Image/telephone.png'),
    Gallary: require('../../assets/Image/Gallary.png'),
    Boxname: require('../../assets/Image/Boxname.png'),
    locationIcon: require('../../assets/Image/locationIcon.png'),
    size: require('../../assets/Image/size.png'),
    time: require('../../assets/Image/time.png'),
    sportdata: require('../../assets/Image/sportdata.png'),
    rupee: require('../../assets/Image/rupee.png'),
    box1: require('../../assets/Image/box1.png'),
    box2: require('../../assets/Image/box2.png'),
    box3: require('../../assets/Image/box3.png'),
    notification: require('../../assets/Image/notification.png'),
    menu: require('../../assets/Image/menu.png'),
    homebg: require('../../assets/Image/homebg.png'),


    call: require('../../assets/Image/call.png'),
    document: require('../../assets/Image/document.png'),
    filter: require('../../assets/Image/filter.png'),
    history: require('../../assets/Image/history.png'),
    home: require('../../assets/Image/home.png'),
    Locaker: require('../../assets/Image/Locaker.png'),
    Location: require('../../assets/Image/Location.png'),
    logout: require('../../assets/Image/logout.png'),
    multiply: require('../../assets/Image/multiply.png'),
    parking: require('../../assets/Image/parking.png'),
    parking: require('../../assets/Image/parking.png'),
    search: require('../../assets/Image/search.png'),
    water: require('../../assets/Image/water.png'),
    waiting: require('../../assets/Image/waiting.png'),
    bat: require('../../assets/Image/bat.png'),
    backbg: require('../../assets/Image/backbg.png'),
    share: require('../../assets/Image/share.png'),
    backScreen: require('../../assets/Image/backScreen.png'),
    headerbg: require('../../assets/Image/headerbg.png'),
    arrowdown: require('../../assets/Image/arrowdown.png'),
    loack: require('../../assets/Image/loack.png'),
    upi: require('../../assets/Image/upi.png'),

    vollyball: require('../../assets/Image/vollyball.jpg'),
    tablete: require('../../assets/Image/tablete.jpg'),
    football: require('../../assets/Image/football.jpg'),
    golf: require('../../assets/Image/golf.jpg'),
    footballplayer: require('../../assets/Image/footballplayer.gif'),
}
